bar:
  height: 24
  location: bottom
  background: 2b3339ff
  foreground: d3c6aaff
  font: monospace:pixelsize=14

  right:
    - battery:
        name: BAT0
        content:
          string:
            text: "BAT[{capacity}] "
    - clock:
        date-format: "%d.%m"
        content:
          - string: 
              text: "{date}"
              right-margin: 6
          - string: 
              text: "{time}"
              right-margin: 3
  center:
    - i3:
        content:
          current:
            string: 
              text: "{title}"
          "":
            string:
              text: ""
  left:
    - i3:
        sort: ascending
        content:
          "":
            map:
              default: 
                string: 
                  text: "{name}"
                  margin: 6
              conditions:
                state == focused:
                  string:
                    text: "{name}"
                    margin: 6
                    foreground: d3c6aaff
                    deco:
                      stack:
                        - background: {color: 4b565cff}


