bar:
  height: 24
  location: bottom
  background: 2b3339ff
  foreground: d3c6aaff
  font: monospace:pixelsize=14

  right:
    - clock:
        date-format: "%d.%m"
        content:
          - string: 
              text: "{date}"
              right-margin: 6
          - string: 
              text: "{time}"
              right-margin: 3
  center:
    - i3:
        content:
          current:
            string: 
              text: "{title}"
          "":
            string:
              text: ""
  left:
    - i3:
        sort: ascending
        content:
          "":
            map:
              tag: state
              default: 
                string: 
                  text: "{name}"
                  margin: 6
              values:
                focused:
                  string:
                    text: "{name}"
                    margin: 6
                    foreground: d3c6aaff
                    deco:
                      stack:
                        - background: {color: 4b565cff}
          current:
            map:
              tag: mode
              values:
                resize:
                  string:
                    text: "resize"
                    margin: 6
                    foreground: 21252bff
                    deco:
                      stack:
                        - background: {color: 98c379ff}


